config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"

  resources :users
  resources :posts do
    resources :comments
  end

  get '/search', to: "posts#search"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :body, presence: true, length: { minimum: 1 }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  validates :title, :body, presence: true, length: { minimum: 1 }

  def self.search(query)
    title_matches = where('title LIKE ?', "%#{query}%")
    body_matches = where('body LIKE ?', "%#{query}%")

    title_matches + (body_matches - title_matches)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
  validates :username, :email, :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username email password password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[username email password password_confirmation])
  end
end

app/controllers/comments_controller.rb
# CommentsController
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      flash[:success] = 'Comment created successfully.'
      redirect_to @comment
    else
      flash[:error] = 'There was a problem creating the comment.'
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update(comment_params)
      flash[:notice] = 'Comment has been updated'
      redirect_to @comment
    else
      flash[:error] = 'Comment could not be updated'
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to comments_path
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :user_id, :post_id)
  end
end

app/controllers/posts_controller.rb
# PostsController
class PostsController < ApplicationController
  before_action :require_login,  only: %i[create edit update]
  def index
    @posts = if params[:search]
      Post.search(params[:search])
    else
      Post.all
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = 'Post created successfully.'
      redirect_to @post
    else
      flash[:error] = 'There was a problem creating the post.'
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      flash[:notice] = 'Post has been updated'
      redirect_to @post
    else
      flash[:error] = 'Post could not be updated'
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :user_id)
  end

  def require_login
    return if current_user

    flash[:error] = 'You must be logged in to access this section'
    redirect_to new_user_session_path
  end
end

app/controllers/users_controller.rb
# UsersController
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'User created successfully.'
      redirect_to @user
    else
      flash[:error] = 'There was a problem creating the user.'
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:notice] = 'User has been updated'
      redirect_to @user
    else
      flash[:error] = 'User could not be updated'
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="main-container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |form| %>
  <% flash.each do |type, message| %>
   <div class="alert alert-<%= type %>">
      <%= message %>
   </div>
  <% end %>

  <div class='field'>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class='field'>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <%= form.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>
    Edit Post
</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="main-container flex flex-col m-0 p-0 w-100">
  <div class="header h-25 w-full bg-gray-500 flex justify-between items-center p-6">
    <div class="logo">
      <h1 class="font-mono font-black text-2xl text-white">
        The Clubhouse
      </h1>
    </div>
    <div class="search text-lg">
      <%= form_tag "/posts", method: "GET" do %>
        <%# <%= label_tag :search_post %> 
        <%= text_field_tag :search, params[:search], placeholder: "Search Posts", class: "bg-white focus:outline-none focus:shadow-outline border border-gray-600 rounded-xl py-2 px-4 block appearance-none leading-normal text-right"%>
        <% submit_tag "Search" %>
      <% end %>
    </div>
    <div class="current-user">
      <% if current_user %>
      <p><%= current_user.username %></p>
      <p><%= link_to 'Create New Post', new_post_path %></p>
      <p><%= button_to(
        "Log Out",
        destroy_user_session_path,
        method: :delete
        ) %>
      </p>
      <% else %>
      <p>
        <%= link_to 'Login', new_user_session_path %>
        <%= link_to 'Sign in', new_user_registration_path %>
      </p>
      <% end %>

    </div>
  </div>
  <div class="content  justify-center grid gap-5 grid-cols-4">
      <div class="posts col-span-3">
        <% @posts.each do |post| %>
          <%= link_to post_path(post) do %>
            <div class="bg-white shadow-md rounded p-4 m-4">
              <div class="post-header flex items-start">
                <div class="title-username flex">
                  <h1 class="text-xl font-bold pl-0">
                    <%= post.title %> 
                  </h1>
                  <% if current_user %>
                    <p>
                      (<%= link_to post.user.username, user_path(post.user) %>)
                    </p>
                  <% end %>
                </div>
                <p class="text-right ml-auto">
                  Posted on <%= post.created_at.strftime("%B %d, %Y") %>
                </p>
              </div>
              <hr>
              <p class="">
                <%= post.body %>
              </p>
            </div>
          <% end %>
        <% end %>
     </div>
     <div class="advert bg-slate-100 p-5 col-span-1">
       <%= link_to "advertisement", "https://www.example.com" %>
     </div>

  </div>
  <div class="footer"></div>
</div>

app/views/posts/new.html.erb
<h1>
    New Post
</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1>
  <%= @post.title %>
</h1>
<p>
  <%= @post.body %>
</p>
<% if current_user %>
  <p>
    Author : <%= @post.user.username %>
  </p>
  <% if current_user == @post.user %>
    <%= link_to 'Edit' , edit_post_path(@post)%>
    <%= link_to 'Delete', post_path(@post), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
  <% end %>
<% end %>
<%= link_to 'Back' , posts_path %>

app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |form| %>
  <% flash.each do |type, message| %>
   <div class="alert alert-<%= type %>">
      <%= message %>
   </div>
  <% end %>

  <div class='field'>
    <%= form.label :username %>
    <%= form.text_field :username, autofocus: true, autocomplete: "username"%>
  </div>

  <div class='field'>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class='field'>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <%= form.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>
    Edit User
</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-3xl font-bold underline">
    user index file
</h1>

app/views/users/new.html.erb
<h1>
    New User
</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-3xl font-bold underline">
    <%= @user.username %>
</h1>
<h2>
    <%= @user.email %>
</h2>
<div>
    <%# Author : <%= @user.user.username %> 
</div>

<%= link_to 'Edit' , edit_user_path(@user)%>
<%= link_to 'Delete', user_path(@user), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
<%= link_to 'Back' , users_path %>